version: 2
jobs:
  test-e2e:
    docker:
      - image: joincolony/circleci-cypress
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Verify Cypress
          command: yarn verify
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache
      - run:
          name: Test E2e
          command: yarn e2e

workflows:
  version: 2
  build:
    jobs:
      - test-e2e
